name: Build & Deploy to EC2

on:
  push:
    branches:
      - main
    paths:
      - "ansible-config/webapp/**"

  workflow_dispatch:  

jobs:
  deploy:
    name: Build and Run Docker on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy app to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem -r ansible-config/webapp ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/webapp

      - name: SSH and build & run container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/webapp
            docker build -t webapp:latest .
            docker rm -f webapp || true
            docker run -d --name webapp -p 80:80 webapp:latest
          EOF
