name: Build and Deploy to EC2

on:
  push:
    branches:
      - main
    paths:
      - "ansible-config/webapp/**"

  workflow_dispatch:

jobs:
  deploy:
    name: Build, Test and Deploy Docker Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy application code to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem -r ansible-config/webapp ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/webapp

      - name: SSH into EC2 and deploy container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/webapp

            sudo docker rm -f webapp || true
            sudo docker rm -f webapp-test || true
            sudo docker rmi -f webapp:latest || true

            sudo docker build -t webapp:latest .

            sudo docker run -d --name webapp-test -p 8080:80 webapp:latest

            sleep 5

            echo "Testing webapp..."
           STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080)

             if [ "$STATUS" -ne 200 ]; then
            echo "Application test failed with status code $STATUS. Aborting deployment."
            sudo docker logs webapp-test
            sudo docker rm -f webapp-test
            exit 1
            else
             echo "Application responded with 200 OK. Proceeding with deployment."
            fi
            sudo docker rm -f webapp-test

            sudo docker run -d --name webapp -p 80:80 webapp:latest
          
